# Generated by Django 5.2.6 on 2025-09-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_rename_shows_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='actions',
        ),
    ]
