# Generated by Django 5.2.6 on 2025-09-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shows',
            new_name='Show',
        ),
    ]
