# Generated by Django 5.2.6 on 2025-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0003_remove_show_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='Hello World'),
        ),
    ]
