# Generated by Django 5.2.6 on 2025-09-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_ap', '0002_dojo_state_alter_dojo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='old_dojo'),
        ),
    ]
